# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 百度极速版

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0-15/1 * * *'
  watch:
    types: started
  repository_dispatch:
    types: baidu_speed
jobs:
  build:
    env:
      BAIDU_COOKIE: ${{ secrets.BAIDU_COOKIE }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        if: env.BAIDU_COOKIE
        run: |
          git clone https://github.com/1skiwen/MyBackup.git ~/MyBackup
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        if: env.BAIDU_COOKIE
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        if: env.BAIDU_COOKIE
        uses: actions/cache@v2 # 使用 GitHub 官方的缓存 Action。
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }} # 使用 package-lock.json 的 Hash 作为缓存的 key。也可以使用 package.json 代替
      - name: npm install
        if: env.BAIDU_COOKIE
        run: |
          cd ~/MyBackup
          git checkout main
          npm install
      - name: '运行 【百度极速版】'
        if: env.BAIDU_COOKIE
        run: |
          cd ~/MyBackup/Task/baidu
          node baidu_speed.js
        env:
          TZ: Asia/shanghai
          BAIDU_COOKIE: ${{ secrets.BAIDU_COOKIE }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
