name: 百度极速版

on:
    workflow_dispatch:
    schedule:
        - cron: "0 0-15/1 * * *"
    watch:
        types: [started]

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 10.x
              uses: actions/setup-node@v1
              with:
                  node-version: 10.x
            - name: npm install
              run: |
                  npm install
            - name: "运行【百度极速版】"
              run: |
                  node Task/baidu/baidu_speed.js
              env:
                  BBBCK: ${{ secrets.BAIDU_COOKIE }}
